# Credential Service Configuration
server:
  port: 8083

spring:
  application:
    name: credential-service
  datasource:
    url: jdbc:mysql://localhost:3306/credential_db
    username: credential_user
    password: credential_pass

# Credential service specific configurations
credential:
  encryption:
    algorithm: AES-GCM
    key: defaultKey123456789012345678901234
    key-rotation-days: 90
  vault:
    enable-audit-log: true
    max-credential-age-days: 365
    enable-auto-rotation: true
  security:
    require-strong-passwords: true
    password-min-length: 12
    enable-encryption-at-rest: true

# Cache configuration for credentials
spring.cache:
  type: redis
  redis:
    time-to-live: 300000  # 5 minutes for security

# Security settings
security:
  audit:
    enabled: true
    log-all-access: true
  encryption:
    provider: bouncycastle
